//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DX.Data.Xpo.Identity.Persistent
{

    [Persistent(@"DXAlienUserRole")]
    public partial class XpoDxAlienUserRole : XPObject
    {
        XpoDxUser _User;
        [Association(@"XpoDxExtendedUserRoleReferencesXpoDxUser")]
        public XpoDxUser User
        {
            get { return _User; }
            set { SetPropertyValue<XpoDxUser>("User", ref _User, value); }
        }
        XpoDxRole _Role;
        [Association(@"XpoDxExtendedUserRoleReferencesXpoDxRole")]
        public XpoDxRole Role
        {
            get { return _Role; }
            set { SetPropertyValue<XpoDxRole>("Role", ref _Role, value); }
        }
        int _AlienID;
        public int AlienID
        {
            get { return _AlienID; }
            set { SetPropertyValue<int>("AlienID", ref _AlienID, value); }
        }
    }

}
